### ISSUE TITLE
Some URLs crash

### ISSUE THREAD

**Issue by jmervine** [jmervine/node-yslowjs#1]
Some URLs crash, e.g.

http://edition.cnn.com/

**Comment by jmervine** [comment]
Occuring because error is being returned from PhantomJS:

```
Error: pure virtual method called
terminate called without an active exception
PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/10b38b66-6455-1ce0-51a6eb76-45dd1884.dmp
```

**Comment by jmervine** [comment]
See: https://github.com/ariya/phantomjs/issues/10666

**Comment by jart** [comment]
Oh wow, is this finally going to be fixed?

**Comment by jmervine** [comment]
I looks like Ariya closed it as "WontFix" stating that it's a firewall issue. I commented on the issue asking for further investigation.

**Comment by davidsonfellipe** [comment]
More one: http://www.eventick.com.br/

**Comment by jmervine** [comment]
Run 'npm update yslowjs' to get version 0.3.0. Check the example in the readme, as I'm now passing error and result instead of just result to the callback. This update doesn't fix the phantomjs issue, but it should keep the node process from crashing if you handle the error.

**Comment by davidsonfellipe** [comment]
@jmervine OK, tested, and now Node process is handling the error. thanks!
